/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev */

#include "oneof.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SubMsg1, SubMsg1, AUTO)


PB_BIND(SubMsg2, SubMsg2, AUTO)


PB_BIND(TopMsg, TopMsg, AUTO)




/* @@protoc_insertion_point(eof) */
