# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/oneof.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/oneof.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0fsrc/oneof.proto\"$\n\x07SubMsg1\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0b\n\x03val\x18\x02 \x01(\x05\"&\n\x07SubMsg2\x12\r\n\x05texts\x18\x01 \x03(\t\x12\x0c\n\x04vals\x18\x02 \x03(\x05\"\x80\x01\n\x06TopMsg\x12\x0e\n\x06sfield\x18\x01 \x01(\t\x12\x0e\n\x06ifield\x18\x02 \x01(\x05\x12\x17\n\x04type\x18\x03 \x01(\x0e\x32\t.MSG_TYPE\x12\x18\n\x04sub1\x18( \x01(\x0b\x32\x08.SubMsg1H\x00\x12\x18\n\x04sub2\x18\x32 \x01(\x0b\x32\x08.SubMsg2H\x00\x42\t\n\x07payload*=\n\x08MSG_TYPE\x12\x11\n\rMSG_TYPE_NONE\x10\x00\x12\x0e\n\nMSG_TYPE_1\x10\x01\x12\x0e\n\nMSG_TYPE_2\x10\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_MSG_TYPE = _descriptor.EnumDescriptor(
  name='MSG_TYPE',
  full_name='MSG_TYPE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MSG_TYPE_NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_TYPE_1', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_TYPE_2', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=228,
  serialized_end=289,
)
_sym_db.RegisterEnumDescriptor(_MSG_TYPE)

MSG_TYPE = enum_type_wrapper.EnumTypeWrapper(_MSG_TYPE)
MSG_TYPE_NONE = 0
MSG_TYPE_1 = 1
MSG_TYPE_2 = 2



_SUBMSG1 = _descriptor.Descriptor(
  name='SubMsg1',
  full_name='SubMsg1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='SubMsg1.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='val', full_name='SubMsg1.val', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=55,
)


_SUBMSG2 = _descriptor.Descriptor(
  name='SubMsg2',
  full_name='SubMsg2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='texts', full_name='SubMsg2.texts', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vals', full_name='SubMsg2.vals', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=95,
)


_TOPMSG = _descriptor.Descriptor(
  name='TopMsg',
  full_name='TopMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sfield', full_name='TopMsg.sfield', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ifield', full_name='TopMsg.ifield', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='TopMsg.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sub1', full_name='TopMsg.sub1', index=3,
      number=40, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sub2', full_name='TopMsg.sub2', index=4,
      number=50, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='TopMsg.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=98,
  serialized_end=226,
)

_TOPMSG.fields_by_name['type'].enum_type = _MSG_TYPE
_TOPMSG.fields_by_name['sub1'].message_type = _SUBMSG1
_TOPMSG.fields_by_name['sub2'].message_type = _SUBMSG2
_TOPMSG.oneofs_by_name['payload'].fields.append(
  _TOPMSG.fields_by_name['sub1'])
_TOPMSG.fields_by_name['sub1'].containing_oneof = _TOPMSG.oneofs_by_name['payload']
_TOPMSG.oneofs_by_name['payload'].fields.append(
  _TOPMSG.fields_by_name['sub2'])
_TOPMSG.fields_by_name['sub2'].containing_oneof = _TOPMSG.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['SubMsg1'] = _SUBMSG1
DESCRIPTOR.message_types_by_name['SubMsg2'] = _SUBMSG2
DESCRIPTOR.message_types_by_name['TopMsg'] = _TOPMSG
DESCRIPTOR.enum_types_by_name['MSG_TYPE'] = _MSG_TYPE

SubMsg1 = _reflection.GeneratedProtocolMessageType('SubMsg1', (_message.Message,), dict(
  DESCRIPTOR = _SUBMSG1,
  __module__ = 'src.oneof_pb2'
  # @@protoc_insertion_point(class_scope:SubMsg1)
  ))
_sym_db.RegisterMessage(SubMsg1)

SubMsg2 = _reflection.GeneratedProtocolMessageType('SubMsg2', (_message.Message,), dict(
  DESCRIPTOR = _SUBMSG2,
  __module__ = 'src.oneof_pb2'
  # @@protoc_insertion_point(class_scope:SubMsg2)
  ))
_sym_db.RegisterMessage(SubMsg2)

TopMsg = _reflection.GeneratedProtocolMessageType('TopMsg', (_message.Message,), dict(
  DESCRIPTOR = _TOPMSG,
  __module__ = 'src.oneof_pb2'
  # @@protoc_insertion_point(class_scope:TopMsg)
  ))
_sym_db.RegisterMessage(TopMsg)


# @@protoc_insertion_point(module_scope)
